version: "3.7"
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      target: "dev"
    env_file:
     - .env
    volumes:
     - ./:/app
    ports:
      - "3000:3000"